name: Update API Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'spec/openapi.yaml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Validate OpenAPI spec
      - name: Validate OpenAPI Spec
        uses: swagger-api/validator-action@v1
        with:
          file: spec/openapi.yaml

      # Step 3: Copy spec to docs folder
      - name: Copy spec file
        run: cp spec/openapi.yaml docs/openapi.yaml

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

      # Step 5: Send Slack Notification
      - name: Notify Slack
        if: success()
        uses: slackapi/slack-github-action@v1.27.0
        with:
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: 'C01R27LF962'
          text: 'API Documentation updated successfully! View at ${{ github.event.repository.html_url }}/pages'